export const FLAGS: Record<string, string> = {
  Norway: '🇳🇴',
  Argentina: '🇦🇷',
  Brazil: '🇧🇷',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Spain: '🇪🇸',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  Croatia: '🇭🇷',
  Denmark: '🇩🇰',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Poland: '🇵🇱',
  'United States': '🇺🇸',
  Mexico: '🇲🇽',
  Canada: '🇨🇦',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  Uruguay: '🇺🇾',
  Colombia: '🇨🇴',
  Ecuador: '🇪🇨',
  Chile: '🇨🇱',
  Peru: '🇵🇪',
  Serbia: '🇷🇸',
  Ukraine: '🇺🇦',
  Austria: '🇦🇹',
  Turkey: '🇹🇷',
  'Saudi Arabia': '🇸🇦',
  Ghana: '🇬🇭',
  Cameroon: '🇨🇲',
  Nigeria: '🇳🇬',
  'Ivory Coast': '🇨🇮',
  'Costa Rica': '🇨🇷',
  Panama: '🇵🇦',
  Qatar: '🇶🇦',
  Iran: '🇮🇷',
  'Czech Republic': '🇨🇿',
  Hungary: '🇭🇺',
  Romania: '🇷🇴',
  Algeria: '🇩🇿',
  Tunisia: '🇹🇳',
  Egypt: '🇪🇬',
  'South Africa': '🇿🇦',
  Jamaica: '🇯🇲',
  Venezuela: '🇻🇪',
  Bolivia: '🇧🇴',
  Paraguay: '🇵🇾',
}

export function flag(team: string): string {
  return FLAGS[team] ?? '🏳️'
}
